server:
  port: 8002
spring:
  profiles:
    active: dev
  application:
    name: byyeungc-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
  instance:
  lease-renewal-interval-in-seconds: 1
  lease-expiration-duration-in-seconds: 2 

  register-with-eureka: true
  fetch-registry: true


