spring:
  redis:
    host: 10.1.0.2
    password: 123456
    database: 0  
    port: 6379  
    pool:
      max-idle: 8 
      min-idle: 0 
      max-active: 8
      max-wait: -1 
      timeout: 0
      
  datasource:
    minIdle: 1
    validationQuery: SELECT 1 FROM DUAL 
    initialSize: 1
    maxWait: 60000
    filters: stat
    poolPreparedStatements: true
    url: jdbc:mysql://10.1.0.10/zz_ent_users?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    testOnBorrow: false
    maxOpenPreparedStatements: 20
    testWhileIdle: true
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20

  data:
     mongodb:
       uri: mongodb://zzent:123456@10.1.0.2:27017/ZZ_ENT_WXAPP_USERS
       
 
